name: dogana
channels:
- pytorch
- defaults
dependencies:
- python=3.6
- pytorch=1.7.0
- scipy
- opencv
- pip:
  - dominate==2.4.0
  - torchvision==0.8.1
  - Pillow==8.0.1
  - numpy==1.16.4
  - visdom==0.1.8
  - packaging==20.4
  - GPUtil==1.4.0
  - wandb == 0.10.10
  - scikit-image == 0.17.2
